




import React from 'react';
import { ScanLine, BookOpen, TrendingUp, Repeat, ShoppingBag, User, Search, Filter, Plus, Minus, X, Check, ChevronRight, ChevronLeft, Settings, Edit2, Trophy, Zap, Eye, EyeOff, LogIn, SlidersHorizontal, List, BarChart2, Shuffle, ArrowUp, ArrowDown, Globe, Layers, CheckCircle, LayoutGrid, Grid, Maximize, ChevronDown, ChevronUp, Trash2, Bell, Star, ExternalLink, TrendingDown, CheckSquare, Square, FolderInput, Activity, PieChart, Briefcase, DollarSign, Lock, MessageSquare, UploadCloud, FileSpreadsheet, FileText, Download, MapPin, Save, Play, Pause, Tag, Calendar, MoreVertical, GripHorizontal, Users, Share2, Shield, MessageCircle, UserPlus, Send, ArrowRight, Box, Clock, Database, Heart } from 'lucide-react';

export const Icons = {
  Scan: ScanLine,
  Binder: BookOpen,
  Market: BarChart2,
  BarChart2: BarChart2,
  Trade: Shuffle,
  Shuffle: Shuffle,
  Flea: ShoppingBag,
  Profile: User,
  Search: Search,
  Filter: Filter,
  Plus: Plus,
  Minus: Minus,
  Close: X,
  Check: Check,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronDown: ChevronDown,
  ChevronUp: ChevronUp,
  Repeat: Repeat,
  Settings: Settings,
  Edit: Edit2,
  Trophy: Trophy,
  Zap: Zap,
  Eye: Eye,
  EyeOff: EyeOff,
  LogIn: LogIn,
  SlidersHorizontal: SlidersHorizontal,
  List: List,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowRight: ArrowRight,
  Globe: Globe,
  Layers: Layers,
  CheckCircle: CheckCircle,
  Grid: Grid,
  LayoutGrid: LayoutGrid,
  Maximize: Maximize,
  Trash2: Trash2,
  Bell: Bell,
  Star: Star,
  ExternalLink: ExternalLink,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  CheckSquare: CheckSquare,
  Square: Square,
  FolderInput: FolderInput,
  Activity: Activity,
  PieChart: PieChart,
  Briefcase: Briefcase,
  DollarSign: DollarSign,
  Lock: Lock,
  MessageSquare: MessageSquare,
  UploadCloud: UploadCloud,
  FileSpreadsheet: FileSpreadsheet,
  FileText: FileText,
  Download: Download,
  MapPin: MapPin,
  Save: Save,
  Play: Play,
  Pause: Pause,
  Tag: Tag,
  Calendar: Calendar,
  ShoppingBag: ShoppingBag,
  MoreVertical: MoreVertical,
  GripHorizontal: GripHorizontal,
  Users: Users,
  Share: Share2,
  Shield: Shield,
  UserPlus: UserPlus,
  Send: Send,
  MessageCircle: MessageCircle,
  Box: Box,
  Clock: Clock,
  Database: Database,
  Heart: Heart
};